export class PlotContent {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly id?: number;

    // Plant name
    name: string;

    // self-explanatory
    days_to_harvest: number;

    // Date the entry was marked as removed
    ended_at?: Date;

    // Date the entry was added to the database
    created_at?: Date;

    // Maxiumum height in mm the plant is expected to grow.
    note: string;

    //position on the plot where plant is at (1-14)
    plot_position: number;



}