export class PlotContent {

    // DB assigned ID. Should only be generated by DB, therefore is readonly.
    readonly id?: number;

    // Date the plant was planted.
    planted_at: Date;

    // Plant type ID of the plant
    PLANT_TYPES_id: number;

    // Plot posistion ID of the plant
    PLOT_POSITIONS_id: number;

    // Date the data entry was marked as ended. Kept for accounting purposes.
    ended_at?: Date;

    // Date the data entry was created. Kept for accounting purposes.
    created_at?: Date;

}

export default PlotContent;