export class Plant {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly id?: number;

    // Plant name
    name: string;

    // maximum depth in mm to plant the seeds
    height?: number;

    // minimum depth in mm to plant the seeds
    width?: number;

    // traget planting depth. Will average max and min if not directly provided.
    depth: number;

    // self-explanatory
    days_to_harvest: number;

    // Date the entry was marked as removed
    ended_at?: Date;

    // Date the entry was added to the database
    created_at?: Date;

    // Maxiumum height in mm the plant is expected to grow.
    description: string;

}